VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|

  # os image
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.synced_folder ".", "/vagrant"

  # server
  config.vm.define "jboss" do |jboss|

        # hostname
        jboss.vm.hostname = "jboss.cc.de"
        # public network
	jboss.vm.network "public_network", :bridge => "eth0"
        # private network
	# jboss.vm.network "private_network", ip: "10.0.1.111"
        jboss.vm.provider "jboss" do |jboss|
                jboss.customize ["modifyvm", :id, "--memory", "1024"]
        end

        # Set the Timezone
        config.vm.provision :shell, :inline => "echo \"Europe/Berlin\" | sudo tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata"

        # upgrade puppet
        jboss.vm.provision :shell, :path => "upgrade-puppet.sh"

        # provisioning with puppet
        jboss.vm.provision "puppet" do |puppet|
                puppet.manifests_path = "manifests"
                puppet.manifest_file = "init.pp"
                puppet.module_path = "modules"
		puppet.options = "--hiera_config /vagrant/files/hiera.yaml"
        end
  end
end
